/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Finance;

import java.awt.event.MouseListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author lahir
 */
public class Cheques extends javax.swing.JInternalFrame {

    /**
     * Creates new form checks
     */
    
    static String x;
    
    public Cheques() {
        initComponents();
        nonMove();
        
        //this.getRootPane().setWindowDecorationStyle(8);
        //UImanager.put("this.active");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        paidCheques = new javax.swing.JButton();
        receivedCheques = new javax.swing.JButton();

        setBackground(new java.awt.Color(76, 77, 78));
        setBorder(null);
        setTitle("Cheques");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1279, 720));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        paidCheques.setBackground(new java.awt.Color(0, 112, 112));
        paidCheques.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        paidCheques.setText("Paid Cheques");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.ipady = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(180, 70, 182, 180);
        getContentPane().add(paidCheques, gridBagConstraints);

        receivedCheques.setBackground(new java.awt.Color(24, 150, 150));
        receivedCheques.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        receivedCheques.setText("Recieved Cheques");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(180, 190, 182, 0);
        getContentPane().add(receivedCheques, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final void nonMove()
        {
            //make the jframe non-movable
        BasicInternalFrameUI frame = ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI());
        for(MouseListener listener: frame.getNorthPane().getMouseListeners())
        {
            frame.getNorthPane().removeMouseListener(listener);
        }
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton paidCheques;
    private javax.swing.JButton receivedCheques;
    // End of variables declaration//GEN-END:variables
}
